### ISSUE TITLE
Pypi version

### ISSUE THREAD

**Issue by Phyks** [kanzure/pdfparanoia#40]
Hello,

https://github.com/kanzure/pdfparanoia/commit/380bc289b33eeaf175dd9cce524161ef289c28fc was not replicated to Pypi and thus, the Pypi version is not working anymore.

**Comment by Phyks** [comment]
Any news on this? Thanks

**Comment by kanzure** [comment]
@Phyks, v16 has now been pushed to pypi.

**Comment by Phyks** [comment]
Thanks!
