### ISSUE TITLE
Initialize no longer needed

### ISSUE THREAD

**Issue by Phyks** [kanzure/pdfparanoia#41]
Hello,

According to [this page](http://www.unixuser.org/~euske/python/pdfminer/), initialize is no longer needed :
````
2014/03/24: Bugfixes and improvements for fauly PDFs.
API changes:

    PDFDocument.initialize() method is removed and no longer needed. A password is given as an argument of a PDFDocument constructor. 
````

**Comment by Phyks** [comment]
Did I miss something, or do you confirm [this](https://github.com/kanzure/pdfparanoia/blob/1a01757f44a6287c448e348c1f9cca1fe4db8ad6/pdfparanoia/parser.py#L35) can be safely removed? Do you want a PR for this?

**Comment by kanzure** [comment]
Yeah #43 still needs a little bit more review, but it's probably ready.

**Comment by Phyks** [comment]
Ok, so closing this issue as it is handled by #43.
